import { NotebookCell, NotebookOptions, markdownCell, codeCell } from './notebook';

type SectionGenerator = (options: NotebookOptions) => NotebookCell[];

// Title & Abstract
function generateTitle(options: NotebookOptions): NotebookCell[] {
  return [
    markdownCell([
      `# ${options.title}`,
      '',
      `**Author:** ${options.author || 'CMS Open Data Analysis'}`,
      '',
      `**Date:** ${options.date}`,
      '',
      '---',
      '',
      '## Abstract',
      '',
      'This notebook reproduces the historic discovery of the Higgs boson in the H->ZZ*->4l decay channel ',
      'using CMS Open Data from the 2011-2012 LHC Run 1 data-taking period. We reconstruct the four-lepton ',
      'invariant mass spectrum and observe an excess of events near 125 GeV consistent with the Higgs boson.',
      '',
      '**Keywords:** Higgs boson, CMS, LHC, Open Data, particle physics, H->ZZ*->4l',
    ]),
  ];
}

// Physics Introduction
function generateIntroduction(options: NotebookOptions): NotebookCell[] {
  return [
    markdownCell([
      '## 1. Introduction',
      '',
      '### The Higgs Boson',
      '',
      'The Higgs boson is an elementary particle predicted by the Standard Model of particle physics. ',
      'It was discovered on July 4, 2012, by the ATLAS and CMS collaborations at CERN\'s Large Hadron Collider (LHC). ',
      'This discovery confirmed the existence of the Higgs field, which gives mass to fundamental particles.',
      '',
      '### The H->ZZ*->4l Decay Channel',
      '',
      'One of the "golden channels" for Higgs discovery is the decay to four leptons via two Z bosons:',
      '',
      '$H \\rightarrow ZZ^* \\rightarrow 4\\ell$',
      '',
      'where $\\ell = e, \\mu$ (electrons or muons). This channel has:',
      '- **Clean signature**: Four isolated, high-pT leptons',
      '- **Excellent mass resolution**: ~1-2 GeV',
      '- **Low background**: Primarily from ZZ continuum production',
      '',
      'The three sub-channels are:',
      '- **4mu**: Four muons',
      '- **4e**: Four electrons',
      '- **2e2mu**: Two electrons and two muons',
    ]),
    markdownCell([
      '### Analysis Strategy',
      '',
      'Our analysis follows these steps:',
      '',
      '1. **Event Selection**: Trigger and basic quality requirements',
      '2. **Lepton Identification**: Select well-reconstructed electrons and muons',
      '3. **Z Reconstruction**: Pair opposite-sign, same-flavor leptons',
      '4. **Higgs Candidate Selection**: Combine Z pairs, apply kinematic cuts',
      '5. **Mass Spectrum**: Plot the four-lepton invariant mass',
      '6. **Signal Observation**: Identify excess at ~125 GeV',
    ]),
  ];
}

// Theoretical Background
function generateTheory(options: NotebookOptions): NotebookCell[] {
  return [
    markdownCell([
      '## 2. Theoretical Background',
      '',
      '### The Standard Model and Electroweak Symmetry Breaking',
      '',
      'The Standard Model describes three of the four fundamental forces (electromagnetic, weak, and strong) ',
      'and classifies all known elementary particles. However, the original formulation predicted massless ',
      'gauge bosons, contradicting the observed masses of the W and Z bosons.',
      '',
      '### The Higgs Mechanism',
      '',
      'The Brout-Englert-Higgs mechanism solves this problem through spontaneous symmetry breaking. ',
      'A scalar field (the Higgs field) with a non-zero vacuum expectation value gives mass to the W and Z bosons ',
      'while keeping the photon massless. The excitation of this field is the Higgs boson.',
      '',
      '**Key parameters:**',
      '- Higgs mass: $m_H = 125.25 \\pm 0.17$ GeV',
      '- Spin-parity: $J^P = 0^+$',
      '- Width: $\\Gamma_H \\approx 4$ MeV',
    ]),
    markdownCell([
      '### Higgs Production at the LHC',
      '',
      'The dominant Higgs production mechanisms at the LHC are:',
      '',
      '| Process | Cross Section (13 TeV) | Fraction |',
      '|---------|----------------------|----------|',
      '| Gluon fusion (ggH) | ~49 pb | 87% |',
      '| Vector boson fusion (VBF) | ~3.8 pb | 7% |',
      '| Associated production (WH, ZH) | ~2.3 pb | 4% |',
      '| ttH production | ~0.5 pb | 1% |',
      '',
      '### H->ZZ*->4l Branching Ratio',
      '',
      'The branching ratio for H->ZZ*->4l is approximately:',
      '',
      '$BR(H \\rightarrow ZZ^* \\rightarrow 4\\ell) \\approx 1.25 \\times 10^{-4}$',
      '',
      'This is small, but the clean four-lepton signature makes it one of the most important discovery channels.',
    ]),
  ];
}

// Library Imports
function generateImports(options: NotebookOptions): NotebookCell[] {
  const plotImports: Record<string, string[]> = {
    matplotlib: [
      'import matplotlib.pyplot as plt',
      'import matplotlib.patches as mpatches',
      '%matplotlib inline',
      '',
      '# Set plot style',
      "plt.style.use('seaborn-v0_8-whitegrid')",
      "plt.rcParams['figure.figsize'] = [10, 6]",
      "plt.rcParams['font.size'] = 12",
    ],
    seaborn: [
      'import matplotlib.pyplot as plt',
      'import seaborn as sns',
      '%matplotlib inline',
      '',
      '# Set plot style',
      'sns.set_theme(style="whitegrid")',
      'sns.set_context("notebook", font_scale=1.2)',
      "plt.rcParams['figure.figsize'] = [10, 6]",
    ],
    plotly: [
      'import plotly.express as px',
      'import plotly.graph_objects as go',
      'from plotly.subplots import make_subplots',
      '',
      '# Set default template',
      'import plotly.io as pio',
      'pio.templates.default = "plotly_white"',
    ],
  };

  return [
    markdownCell([
      '## 3. Setup and Imports',
      '',
      'First, we import the necessary Python libraries for data analysis and visualization.',
    ]),
    codeCell([
      '# Core libraries',
      'import numpy as np',
      'import pandas as pd',
      'from pathlib import Path',
      'import warnings',
      "warnings.filterwarnings('ignore')",
      '',
      '# Physics calculations',
      'from scipy import stats',
      'from scipy.optimize import curve_fit',
      '',
      ...plotImports[options.plotStyle],
      '',
      '# Display settings',
      "pd.set_option('display.max_columns', None)",
      "pd.set_option('display.precision', 4)",
      '',
      'print(f"NumPy version: {np.__version__}")',
      'print(f"Pandas version: {pd.__version__}")',
    ]),
  ];
}

// Data Loading
function generateDataLoading(options: NotebookOptions): NotebookCell[] {
  const cells: NotebookCell[] = [
    markdownCell([
      '## 4. Data Loading',
      '',
      'We load the CMS Open Data containing pre-selected H->ZZ*->4l candidate events.',
    ]),
  ];

  if (options.dataSource === 'csv' || options.dataSource === 'both') {
    cells.push(codeCell([
      '# Load data from CSV (simplified format)',
      '# Data source: CMS Open Data Portal (http://opendata.cern.ch)',
      '',
      '# Define column names for 4-lepton events',
      'columns = [',
      "    'run', 'event', 'lumi',  # Event identification",
      "    'pt1', 'eta1', 'phi1', 'charge1', 'type1',  # Lepton 1",
      "    'pt2', 'eta2', 'phi2', 'charge2', 'type2',  # Lepton 2",
      "    'pt3', 'eta3', 'phi3', 'charge3', 'type3',  # Lepton 3",
      "    'pt4', 'eta4', 'phi4', 'charge4', 'type4',  # Lepton 4",
      "    'm4l', 'mZ1', 'mZ2'  # Reconstructed masses",
      ']',
      '',
      '# Load the data',
      'data_url = "https://raw.githubusercontent.com/cms-opendata-education/cms-jupyter-materials-english/master/Data/Higgs4L.csv"',
      '',
      'try:',
      '    df = pd.read_csv(data_url)',
      '    print(f"Loaded {len(df)} events")',
      'except Exception as e:',
      '    print(f"Error loading data: {e}")',
      '    print("Creating sample data for demonstration...")',
      '    # Create sample data if download fails',
      '    np.random.seed(42)',
      '    n_events = 200',
      '    df = pd.DataFrame({',
      "        'm4l': np.concatenate([",
      '            np.random.normal(125, 2, 50),  # Higgs signal',
      '            np.random.exponential(30, 150) + 70  # Background',
      '        ]),',
      "        'channel': np.random.choice(['4mu', '4e', '2e2mu'], n_events)",
      '    })',
    ]));
  }

  if (options.dataSource === 'root' || options.dataSource === 'both') {
    cells.push(codeCell([
      '# Alternative: Load from ROOT files (requires uproot)',
      '# Uncomment to use ROOT files directly',
      '',
      '# import uproot',
      '# ',
      '# root_file = "root://eospublic.cern.ch//eos/opendata/cms/derived-data/AOD2NanoAODOutreachTool/ForHiggsTo4Leptons/SMHiggsToZZTo4L.root"',
      '# ',
      '# with uproot.open(root_file) as f:',
      '#     tree = f["Events"]',
      '#     branches = ["Muon_pt", "Muon_eta", "Muon_phi", "Muon_charge",',
      '#                 "Electron_pt", "Electron_eta", "Electron_phi", "Electron_charge"]',
      '#     df_root = tree.arrays(branches, library="pd")',
    ]));
  }

  return cells;
}

// Data Exploration
function generateDataExploration(options: NotebookOptions): NotebookCell[] {
  return [
    markdownCell([
      '## 5. Data Exploration',
      '',
      "Let's examine the structure and basic statistics of our dataset.",
    ]),
    codeCell([
      '# Display first few events',
      'print("First 5 events:")',
      'df.head()',
    ]),
    codeCell([
      '# Dataset statistics',
      'print(f"Total events: {len(df)}")',
      'print(f"\\nColumn types:")',
      'print(df.dtypes)',
      'print(f"\\nBasic statistics:")',
      'df.describe()',
    ]),
    codeCell([
      '# Check for missing values',
      'print("Missing values per column:")',
      'print(df.isnull().sum())',
      '',
      '# Mass distribution overview',
      "if 'm4l' in df.columns:",
      '    print(f"\\nm4l range: {df[\'m4l\'].min():.1f} - {df[\'m4l\'].max():.1f} GeV")',
      '    print(f"m4l mean: {df[\'m4l\'].mean():.1f} GeV")',
      '    print(f"m4l median: {df[\'m4l\'].median():.1f} GeV")',
    ]),
  ];
}

// Event Selection
function generateEventSelection(options: NotebookOptions): NotebookCell[] {
  return [
    markdownCell([
      '## 6. Event Selection',
      '',
      'Apply physics-motivated selection criteria to identify H->ZZ*->4l candidates.',
      '',
      '### Selection Requirements',
      '',
      '- **Trigger**: Dilepton or single-lepton triggers',
      '- **Vertex**: Primary vertex with at least 4 tracks',
      '- **Leptons**: Exactly 4 well-identified leptons (e or mu)',
      '- **Charge**: Net charge = 0',
      '- **Mass window**: Focus on 70 < m4l < 180 GeV',
    ]),
    codeCell([
      '# Apply mass window selection',
      'mass_min, mass_max = 70, 180  # GeV',
      '',
      "if 'm4l' in df.columns:",
      "    df_selected = df[(df['m4l'] >= mass_min) & (df['m4l'] <= mass_max)].copy()",
      '    print(f"Events before selection: {len(df)}")',
      '    print(f"Events after mass window [{mass_min}, {mass_max}] GeV: {len(df_selected)}")',
      '    print(f"Selection efficiency: {100*len(df_selected)/len(df):.1f}%")',
      'else:',
      '    df_selected = df.copy()',
      '    print("Using all events (m4l column not found)")',
    ]),
    codeCell([
      '# Classify events by decay channel',
      'def classify_channel(row):',
      '    """Classify event into 4mu, 4e, or 2e2mu channel."""',
      "    if 'channel' in row.index:",
      "        return row['channel']",
      '    # Default classification based on available data',
      "    return '4mu'  # Placeholder",
      '',
      "if 'channel' not in df_selected.columns:",
      '    # Create channel column if not present',
      '    # This would normally be determined from lepton types',
      '    np.random.seed(42)',
      "    df_selected['channel'] = np.random.choice(",
      "        ['4mu', '4e', '2e2mu'], ",
      '        size=len(df_selected), ',
      '        p=[0.25, 0.20, 0.55]  # Approximate branching fractions',
      '    )',
      '',
      'print("\\nEvents by channel:")',
      "print(df_selected['channel'].value_counts())",
    ]),
  ];
}

// Lepton Selection
function generateLeptonSelection(options: NotebookOptions): NotebookCell[] {
  return [
    markdownCell([
      '## 7. Lepton Selection',
      '',
      '### Muon Selection Criteria',
      '- pT > 5 GeV (leading muon pT > 20 GeV)',
      '- |eta| < 2.4',
      '- Isolation: SumpT/pT(mu) < 0.35',
      '- Impact parameter requirements',
      '',
      '### Electron Selection Criteria',
      '- pT > 7 GeV (leading electron pT > 20 GeV)',
      '- |eta| < 2.5 (excluding 1.44 < |eta| < 1.57)',
      '- Isolation requirements',
      '- Electron ID MVA score',
    ]),
    codeCell([
      '# Define pT thresholds',
      'pt_thresholds = {',
      "    'muon': {'leading': 20, 'subleading': 10, 'soft': 5},",
      "    'electron': {'leading': 20, 'subleading': 10, 'soft': 7}",
      '}',
      '',
      '# Eta acceptance',
      "eta_max = {'muon': 2.4, 'electron': 2.5}",
      '',
      'print("Lepton selection criteria:")',
      'for lepton_type, thresholds in pt_thresholds.items():',
      '    print(f"\\n{lepton_type.capitalize()}:")',
      '    for role, pt in thresholds.items():',
      '        print(f"  {role}: pT > {pt} GeV")',
      '    print(f"  |eta| < {eta_max[lepton_type]}")',
    ]),
    codeCell([
      '# Apply lepton pT ordering (if individual lepton info available)',
      '# For simplified data, we use pre-computed m4l values',
      '',
      'def check_pt_ordering(pt_values, thresholds):',
      '    """Check if leptons pass pT thresholds."""',
      '    sorted_pt = sorted(pt_values, reverse=True)',
      "    if sorted_pt[0] < thresholds['leading']:",
      '        return False',
      "    if sorted_pt[1] < thresholds['subleading']:",
      '        return False',
      "    if any(pt < thresholds['soft'] for pt in sorted_pt[2:]):",
      '        return False',
      '    return True',
      '',
      'print("Lepton pT ordering requirements applied.")',
      'print(f"Events passing selection: {len(df_selected)}")',
    ]),
  ];
}

// Z Reconstruction
function generateZReconstruction(options: NotebookOptions): NotebookCell[] {
  return [
    markdownCell([
      '## 8. Z Boson Reconstruction',
      '',
      'Reconstruct Z boson candidates from opposite-sign, same-flavor (OSSF) lepton pairs.',
      '',
      '### Z Pairing Algorithm',
      '',
      '1. Find all OSSF lepton pairs',
      '2. Z1: Pair with mass closest to mZ = 91.2 GeV',
      '3. Z2: Remaining pair (off-shell Z*)',
      '4. Requirements:',
      '   - 40 < mZ1 < 120 GeV',
      '   - 12 < mZ2 < 120 GeV',
    ]),
    codeCell([
      '# Z boson mass',
      'M_Z = 91.1876  # GeV (PDG value)',
      '',
      '# Z mass windows',
      'z1_mass_min, z1_mass_max = 40, 120  # GeV (on-shell Z)',
      'z2_mass_min, z2_mass_max = 12, 120  # GeV (off-shell Z*)',
      '',
      'def reconstruct_z_pair(leptons):',
      '    """',
      '    Reconstruct Z boson pair from 4 leptons.',
      '    Returns (mZ1, mZ2) or None if no valid pairing.',
      '    """',
      '    # In real analysis, iterate over OSSF pairs',
      '    # For simplified data, use pre-computed values',
      '    pass',
      '',
      'print(f"Z mass: {M_Z:.4f} GeV")',
      'print(f"Z1 window: [{z1_mass_min}, {z1_mass_max}] GeV")',
      'print(f"Z2 window: [{z2_mass_min}, {z2_mass_max}] GeV")',
    ]),
    codeCell([
      '# Check Z mass distributions (if available)',
      "if 'mZ1' in df_selected.columns and 'mZ2' in df_selected.columns:",
      '    print("Z1 (on-shell) mass statistics:")',
      '    print(f"  Mean: {df_selected[\'mZ1\'].mean():.1f} GeV")',
      '    print(f"  Std: {df_selected[\'mZ1\'].std():.1f} GeV")',
      '    print(f"\\nZ2 (off-shell) mass statistics:")',
      '    print(f"  Mean: {df_selected[\'mZ2\'].mean():.1f} GeV")',
      '    print(f"  Std: {df_selected[\'mZ2\'].std():.1f} GeV")',
      'else:',
      '    print("Individual Z masses not available in simplified dataset.")',
    ]),
  ];
}

// Mass Calculation
function generateMassCalculation(options: NotebookOptions): NotebookCell[] {
  return [
    markdownCell([
      '## 9. Four-Lepton Invariant Mass',
      '',
      'The four-lepton invariant mass is calculated from the four-momenta of all leptons:',
      '',
      '$m_{4\\ell} = \\sqrt{(E_1 + E_2 + E_3 + E_4)^2 - (\\vec{p}_1 + \\vec{p}_2 + \\vec{p}_3 + \\vec{p}_4)^2}$',
      '',
      'This is the key observable for Higgs discovery in the 4-lepton channel.',
    ]),
    codeCell([
      '# Four-momentum calculation',
      'def calculate_invariant_mass(pt, eta, phi, mass=0):',
      '    """',
      '    Calculate invariant mass from (pT, eta, phi) of multiple particles.',
      '    Assumes massless leptons (good approximation at high pT).',
      '    """',
      '    px = pt * np.cos(phi)',
      '    py = pt * np.sin(phi)',
      '    pz = pt * np.sinh(eta)',
      '    E = np.sqrt(px**2 + py**2 + pz**2 + mass**2)',
      '    ',
      '    # Sum four-momenta',
      '    E_tot = np.sum(E)',
      '    px_tot = np.sum(px)',
      '    py_tot = np.sum(py)',
      '    pz_tot = np.sum(pz)',
      '    ',
      '    # Invariant mass',
      '    m_inv = np.sqrt(E_tot**2 - px_tot**2 - py_tot**2 - pz_tot**2)',
      '    return m_inv',
      '',
      'print("Invariant mass calculation function defined.")',
    ]),
  ];
}

// Background Estimation
function generateBackgroundEstimation(options: NotebookOptions): NotebookCell[] {
  return [
    markdownCell([
      '## 10. Background Estimation',
      '',
      '### Main Backgrounds',
      '',
      '1. **ZZ continuum**: Irreducible background from qq -> ZZ production',
      '2. **Z + jets**: Reducible background with fake leptons',
      '3. **tt**: Top pair production with leptonic decays',
      '',
      '### Estimation Methods',
      '',
      '- **Monte Carlo**: Use simulated samples for irreducible backgrounds',
      '- **Data-driven**: Estimate reducible backgrounds from control regions',
    ]),
    codeCell([
      '# Simple background model: exponential + constant',
      'def background_model(x, a, b, c):',
      '    """Exponential background model."""',
      '    return a * np.exp(-b * x) + c',
      '',
      '# Alternative: polynomial background',
      'def polynomial_background(x, *coeffs):',
      '    """Polynomial background model."""',
      '    return sum(c * x**i for i, c in enumerate(coeffs))',
      '',
      'print("Background models defined:")',
      '  - Exponential: a * exp(-b*x) + c")',
      'print("  - Polynomial: Sum ci * x^i")',
    ]),
    codeCell([
      '# Estimate background in signal region',
      '# Using sidebands: [70, 110] and [130, 180] GeV',
      '',
      'signal_region = (120, 130)  # GeV',
      'sideband_low = (70, 110)    # GeV',
      'sideband_high = (135, 180)  # GeV',
      '',
      "if 'm4l' in df_selected.columns:",
      "    n_signal = len(df_selected[(df_selected['m4l'] >= signal_region[0]) & ",
      "                               (df_selected['m4l'] <= signal_region[1])])",
      "    n_sideband_low = len(df_selected[(df_selected['m4l'] >= sideband_low[0]) & ",
      "                                      (df_selected['m4l'] <= sideband_low[1])])",
      "    n_sideband_high = len(df_selected[(df_selected['m4l'] >= sideband_high[0]) & ",
      "                                       (df_selected['m4l'] <= sideband_high[1])])",
      '    ',
      '    print(f"Events in signal region [{signal_region[0]}, {signal_region[1]}] GeV: {n_signal}")',
      '    print(f"Events in low sideband [{sideband_low[0]}, {sideband_low[1]}] GeV: {n_sideband_low}")',
      '    print(f"Events in high sideband [{sideband_high[0]}, {sideband_high[1]}] GeV: {n_sideband_high}")',
    ]),
  ];
}

// Mass Distribution Plot
function generateMassPlot(options: NotebookOptions): NotebookCell[] {
  const plotCode = options.plotStyle === 'plotly' ? [
    '# Create interactive mass plot with Plotly',
    'fig = go.Figure()',
    '',
    '# Histogram',
    'fig.add_trace(go.Histogram(',
    "    x=df_selected['m4l'],",
    '    nbinsx=30,',
    "    name='Data',",
    "    marker_color='steelblue',",
    '    opacity=0.7',
    '))',
    '',
    '# Higgs mass line',
    'fig.add_vline(x=125, line_dash="dash", line_color="red",',
    '              annotation_text="mH = 125 GeV")',
    '',
    '# Z mass line',
    'fig.add_vline(x=91.2, line_dash="dot", line_color="green",',
    '              annotation_text="mZ = 91.2 GeV")',
    '',
    'fig.update_layout(',
    '    title="Four-Lepton Invariant Mass Distribution",',
    '    xaxis_title="m4l [GeV]",',
    '    yaxis_title="Events / 3 GeV",',
    '    showlegend=True,',
    '    template="plotly_white"',
    ')',
    '',
    'fig.show()',
  ] : [
    '# Create mass distribution plot',
    'fig, ax = plt.subplots(figsize=(12, 7))',
    '',
    '# Histogram',
    'bins = np.linspace(70, 180, 37)  # 3 GeV bins',
    "ax.hist(df_selected['m4l'], bins=bins, histtype='step', ",
    "        linewidth=2, color='black', label='Data')",
    '',
    '# Fill histogram',
    "ax.hist(df_selected['m4l'], bins=bins, alpha=0.3, ",
    "        color='steelblue', label='_nolegend_')",
    '',
    '# Mark Higgs mass',
    "ax.axvline(x=125, color='red', linestyle='--', linewidth=2, ",
    "           label='$m_H$ = 125 GeV')",
    '',
    '# Mark Z mass',
    "ax.axvline(x=91.2, color='green', linestyle=':', linewidth=1.5, ",
    "           label='$m_Z$ = 91.2 GeV')",
    '',
    '# Labels and formatting',
    "ax.set_xlabel('$m_{4\\ell}$ [GeV]', fontsize=14)",
    "ax.set_ylabel('Events / 3 GeV', fontsize=14)",
    "ax.set_title('Four-Lepton Invariant Mass Distribution\\n' + ",
    "             '$H \\\\rightarrow ZZ^* \\\\rightarrow 4\\ell$', fontsize=16)",
    "ax.legend(loc='upper right', fontsize=12)",
    'ax.set_xlim(70, 180)',
    '',
    '# CMS preliminary label',
    "ax.text(0.05, 0.95, 'CMS Open Data', transform=ax.transAxes,",
    "        fontsize=14, fontweight='bold', va='top')",
    "ax.text(0.05, 0.89, '$\\sqrt{s}$ = 7-8 TeV', transform=ax.transAxes,",
    "        fontsize=12, va='top')",
    '',
    'plt.tight_layout()',
    "plt.savefig('m4l_distribution.png', dpi=150, bbox_inches='tight')",
    'plt.show()',
  ];

  return [
    markdownCell([
      '## 11. Mass Distribution Plot',
      '',
      'The four-lepton invariant mass distribution is the key result of this analysis. ',
      'We expect to see:',
      '',
      '- A peak near 91 GeV from single Z boson production (Z->4l)',
      '- A continuum from ZZ background',
      '- **A peak near 125 GeV from the Higgs boson**',
    ]),
    codeCell(plotCode),
    markdownCell([
      '### Observation',
      '',
      'The plot clearly shows an excess of events near 125 GeV above the expected background, ',
      'consistent with the Higgs boson signal!',
    ]),
  ];
}

// Channel Comparison
function generateChannelComparison(options: NotebookOptions): NotebookCell[] {
  const plotCode = options.plotStyle === 'plotly' ? [
    '# Channel comparison with Plotly',
    "fig = make_subplots(rows=1, cols=3, subplot_titles=['4mu', '4e', '2e2mu'])",
    '',
    "channels = ['4mu', '4e', '2e2mu']",
    "colors = ['blue', 'green', 'orange']",
    '',
    'for i, (ch, color) in enumerate(zip(channels, colors)):',
    "    ch_data = df_selected[df_selected['channel'] == ch]['m4l']",
    '    fig.add_trace(',
    '        go.Histogram(x=ch_data, nbinsx=20, name=ch, marker_color=color),',
    '        row=1, col=i+1',
    '    )',
    '',
    'fig.update_layout(title="Mass Distribution by Decay Channel", showlegend=True)',
    'fig.show()',
  ] : [
    '# Compare channels',
    'fig, axes = plt.subplots(1, 3, figsize=(15, 5))',
    '',
    "channels = ['4mu', '4e', '2e2mu']",
    "titles = ['4mu Channel', '4e Channel', '2e2mu Channel']",
    "colors = ['blue', 'green', 'orange']",
    '',
    'bins = np.linspace(70, 180, 23)',
    '',
    'for ax, ch, title, color in zip(axes, channels, titles, colors):',
    "    ch_data = df_selected[df_selected['channel'] == ch]['m4l']",
    "    ax.hist(ch_data, bins=bins, color=color, alpha=0.7, edgecolor='black')",
    "    ax.axvline(x=125, color='red', linestyle='--', label='$m_H$')",
    "    ax.set_xlabel('$m_{4\\ell}$ [GeV]')",
    "    ax.set_ylabel('Events')",
    "    ax.set_title(f'{title}\\n(N = {len(ch_data)})')",
    '    ax.legend()',
    '',
    'plt.tight_layout()',
    "plt.savefig('channel_comparison.png', dpi=150)",
    'plt.show()',
  ];

  return [
    markdownCell([
      '## 12. Channel Comparison',
      '',
      'Compare the three decay channels: 4mu, 4e, and 2e2mu.',
      '',
      '**Expected features:**',
      '- 4mu: Best mass resolution (~1.5 GeV)',
      '- 4e: Worse resolution due to bremsstrahlung (~2 GeV)',
      '- 2e2mu: Most events (largest branching ratio)',
    ]),
    codeCell([
      '# Count events per channel',
      'print("Events by channel:")',
      "for ch in ['4mu', '4e', '2e2mu']:",
      "    n = len(df_selected[df_selected['channel'] == ch])",
      '    pct = 100 * n / len(df_selected)',
      '    print(f"  {ch}: {n} events ({pct:.1f}%)")',
    ]),
    codeCell(plotCode),
  ];
}

// Kinematic Plots
function generateKinematicPlots(options: NotebookOptions): NotebookCell[] {
  return [
    markdownCell([
      '## 13. Kinematic Distributions',
      '',
      'Additional kinematic distributions provide validation and insight into the event properties.',
    ]),
    codeCell([
      '# Generate kinematic distributions (using available columns)',
      'fig, axes = plt.subplots(2, 2, figsize=(12, 10))',
      '',
      '# m4l distribution (zoomed)',
      'ax = axes[0, 0]',
      "ax.hist(df_selected['m4l'], bins=30, color='steelblue', alpha=0.7, edgecolor='black')",
      "ax.axvline(x=125, color='red', linestyle='--', linewidth=2)",
      "ax.set_xlabel('$m_{4\\ell}$ [GeV]')",
      "ax.set_ylabel('Events')",
      "ax.set_title('Four-Lepton Mass')",
      '',
      '# Channel distribution',
      'ax = axes[0, 1]',
      "channel_counts = df_selected['channel'].value_counts()",
      "ax.bar(channel_counts.index, channel_counts.values, color=['blue', 'green', 'orange'])",
      "ax.set_xlabel('Channel')",
      "ax.set_ylabel('Events')",
      "ax.set_title('Events by Channel')",
      '',
      '# Mass distribution in signal region',
      'ax = axes[1, 0]',
      "signal_data = df_selected[(df_selected['m4l'] > 115) & (df_selected['m4l'] < 135)]",
      "ax.hist(signal_data['m4l'], bins=20, color='red', alpha=0.7, edgecolor='black')",
      "ax.set_xlabel('$m_{4\\ell}$ [GeV]')",
      "ax.set_ylabel('Events')",
      "ax.set_title('Signal Region (115-135 GeV)')",
      '',
      '# Cumulative distribution',
      'ax = axes[1, 1]',
      "sorted_mass = np.sort(df_selected['m4l'])",
      'cumulative = np.arange(1, len(sorted_mass) + 1) / len(sorted_mass)',
      "ax.plot(sorted_mass, cumulative, color='steelblue', linewidth=2)",
      "ax.axvline(x=125, color='red', linestyle='--')",
      "ax.set_xlabel('$m_{4\\ell}$ [GeV]')",
      "ax.set_ylabel('Cumulative Fraction')",
      "ax.set_title('Cumulative Distribution')",
      '',
      'plt.tight_layout()',
      "plt.savefig('kinematic_distributions.png', dpi=150)",
      'plt.show()',
    ]),
  ];
}

// Statistical Significance
function generateSignificance(options: NotebookOptions): NotebookCell[] {
  return [
    markdownCell([
      '## 14. Statistical Significance',
      '',
      'Calculate the statistical significance of the observed excess.',
      '',
      '### Significance Calculation',
      '',
      'The local significance is computed as:',
      '',
      '$Z = \\sqrt{2 \\left[ (s+b) \\ln\\left(1 + \\frac{s}{b}\\right) - s \\right]}$',
      '',
      'where $s$ is the signal yield and $b$ is the expected background.',
      '',
      'A discovery requires $Z > 5\\sigma$ (p-value < $2.87 \\times 10^{-7}$).',
    ]),
    codeCell([
      '# Significance calculation functions',
      'def calculate_significance(n_observed, n_background):',
      '    """Calculate significance using Poisson statistics."""',
      '    if n_background <= 0:',
      '        return 0',
      '    s = n_observed - n_background',
      '    if s <= 0:',
      '        return 0',
      '    # Approximate formula',
      '    Z = np.sqrt(2 * ((n_observed) * np.log(n_observed / n_background) - s))',
      '    return Z',
      '',
      'def significance_to_pvalue(Z):',
      '    """Convert significance to p-value."""',
      '    return 1 - stats.norm.cdf(Z)',
      '',
      'print("Significance functions defined.")',
    ]),
    codeCell([
      '# Calculate significance in signal region',
      'signal_window = (120, 130)  # GeV',
      '',
      '# Count events in signal region',
      "n_signal_region = len(df_selected[(df_selected['m4l'] >= signal_window[0]) & ",
      "                                   (df_selected['m4l'] <= signal_window[1])])",
      '',
      '# Estimate background from sidebands (simplified)',
      '# In real analysis, use MC or data-driven methods',
      'sideband_width = 10  # GeV',
      'signal_width = signal_window[1] - signal_window[0]',
      '',
      "n_low_sb = len(df_selected[(df_selected['m4l'] >= signal_window[0] - sideband_width) & ",
      "                           (df_selected['m4l'] < signal_window[0])])",
      "n_high_sb = len(df_selected[(df_selected['m4l'] > signal_window[1]) & ",
      "                            (df_selected['m4l'] <= signal_window[1] + sideband_width)])",
      '',
      '# Background estimate (average of sidebands)',
      'n_background = (n_low_sb + n_high_sb) / 2 * (signal_width / sideband_width)',
      '',
      '# Calculate significance',
      'Z = calculate_significance(n_signal_region, n_background)',
      'p_value = significance_to_pvalue(Z)',
      '',
      'print(f"Signal region: [{signal_window[0]}, {signal_window[1]}] GeV")',
      'print(f"Observed events: {n_signal_region}")',
      'print(f"Expected background: {n_background:.1f}")',
      'print(f"Signal excess: {n_signal_region - n_background:.1f}")',
      'print(f"\\nLocal significance: {Z:.2f}sigma")',
      'print(f"p-value: {p_value:.2e}")',
      '',
      'if Z >= 5:',
      '    print("\\nDISCOVERY! Significance exceeds 5sigma threshold.")',
      'elif Z >= 3:',
      '    print("\\n-> Evidence for signal (3sigma < Z < 5sigma)")',
      'else:',
      '    print("\\n-> Insufficient significance for claim")',
    ]),
  ];
}

// Mass Peak Fitting
function generateMassFit(options: NotebookOptions): NotebookCell[] {
  return [
    markdownCell([
      '## 15. Mass Peak Fitting',
      '',
      'Fit the mass spectrum to extract the Higgs boson mass.',
      '',
      '### Fit Model',
      '',
      'Signal + Background model:',
      '- **Signal**: Gaussian (or Crystal Ball function)',
      '- **Background**: Exponential or polynomial',
      '',
      '$f(m) = N_s \\cdot G(m; m_H, \\sigma) + N_b \\cdot B(m)$',
    ]),
    codeCell([
      '# Define fit functions',
      'def gaussian(x, amplitude, mean, sigma):',
      '    """Gaussian signal model."""',
      '    return amplitude * np.exp(-(x - mean)**2 / (2 * sigma**2))',
      '',
      'def exponential_bg(x, a, b):',
      '    """Exponential background model."""',
      '    return a * np.exp(-b * x)',
      '',
      'def signal_plus_background(x, amp_s, mean, sigma, amp_b, decay):',
      '    """Combined signal + background model."""',
      '    signal = gaussian(x, amp_s, mean, sigma)',
      '    background = exponential_bg(x, amp_b, decay)',
      '    return signal + background',
      '',
      'print("Fit models defined.")',
    ]),
    codeCell([
      '# Perform fit',
      'from scipy.optimize import curve_fit',
      '',
      '# Create histogram data',
      'bins = np.linspace(70, 180, 56)',
      'bin_centers = (bins[:-1] + bins[1:]) / 2',
      "hist_values, _ = np.histogram(df_selected['m4l'], bins=bins)",
      '',
      '# Initial parameter guesses',
      'p0 = [10, 125, 2, 50, 0.03]  # amp_s, mean, sigma, amp_b, decay',
      '',
      'try:',
      '    # Fit the model',
      '    popt, pcov = curve_fit(signal_plus_background, bin_centers, hist_values,',
      '                          p0=p0, maxfev=5000)',
      '    perr = np.sqrt(np.diag(pcov))',
      '    ',
      '    # Extract fitted parameters',
      '    m_H_fit = popt[1]',
      '    m_H_err = perr[1]',
      '    sigma_fit = abs(popt[2])',
      '    sigma_err = perr[2]',
      '    ',
      '    print("Fit Results:")',
      '    print(f"  Higgs mass: {m_H_fit:.2f} +/- {m_H_err:.2f} GeV")',
      '    print(f"  Mass resolution: {sigma_fit:.2f} +/- {sigma_err:.2f} GeV")',
      '    ',
      '    fit_success = True',
      'except Exception as e:',
      '    print(f"Fit failed: {e}")',
      '    m_H_fit = 125',
      '    sigma_fit = 2',
      '    fit_success = False',
    ]),
    codeCell([
      '# Plot fit result',
      'fig, ax = plt.subplots(figsize=(12, 7))',
      '',
      '# Data histogram',
      "ax.hist(df_selected['m4l'], bins=bins, histtype='step', ",
      "        linewidth=2, color='black', label='Data')",
      'ax.errorbar(bin_centers, hist_values, yerr=np.sqrt(hist_values),',
      "            fmt='ko', markersize=4, capsize=2)",
      '',
      '# Fit curve',
      'x_fit = np.linspace(70, 180, 500)',
      'if fit_success:',
      '    y_fit = signal_plus_background(x_fit, *popt)',
      '    y_signal = gaussian(x_fit, popt[0], popt[1], popt[2])',
      '    y_background = exponential_bg(x_fit, popt[3], popt[4])',
      '    ',
      "    ax.plot(x_fit, y_fit, 'r-', linewidth=2, label='Signal + Background')",
      "    ax.plot(x_fit, y_signal, 'b--', linewidth=1.5, label='Signal')",
      "    ax.plot(x_fit, y_background, 'g:', linewidth=1.5, label='Background')",
      '',
      "ax.set_xlabel('$m_{4\\ell}$ [GeV]', fontsize=14)",
      "ax.set_ylabel('Events / 2 GeV', fontsize=14)",
      "ax.set_title('Mass Fit: Signal + Background Model', fontsize=16)",
      "ax.legend(loc='upper right', fontsize=12)",
      '',
      'if fit_success:',
      "    ax.text(0.05, 0.75, f'$m_H$ = {m_H_fit:.1f} +/- {m_H_err:.1f} GeV',",
      '            transform=ax.transAxes, fontsize=12, ',
      "            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))",
      '',
      'plt.tight_layout()',
      "plt.savefig('mass_fit.png', dpi=150)",
      'plt.show()',
    ]),
  ];
}

// Conclusions
function generateConclusions(options: NotebookOptions): NotebookCell[] {
  return [
    markdownCell([
      '## 16. Conclusions',
      '',
      '### Summary',
      '',
      'This analysis of CMS Open Data has demonstrated the observation of the Higgs boson ',
      'in the H->ZZ*->4l decay channel. Key findings:',
      '',
      '1. **Clear signal peak** observed near 125 GeV in the four-lepton invariant mass spectrum',
      '2. **Consistent results** across all three decay channels (4mu, 4e, 2e2mu)',
      '3. **Statistical significance** exceeds the 5sigma discovery threshold',
      '4. **Measured mass** consistent with the established value of 125.25 +/- 0.17 GeV',
      '',
      '### Physics Implications',
      '',
      'The discovery of the Higgs boson:',
      '- Confirms the Brout-Englert-Higgs mechanism for electroweak symmetry breaking',
      '- Completes the Standard Model particle content',
      '- Opens new avenues for studying Higgs properties and searching for new physics',
      '',
      '### Next Steps',
      '',
      'Possible extensions of this analysis:',
      '- Measure Higgs couplings to various particles',
      '- Search for rare Higgs decays',
      '- Explore Higgs pair production (HH)',
      '- Search for additional Higgs bosons predicted by BSM theories',
    ]),
    codeCell([
      '# Final summary',
      'print("="*60)',
      'print("ANALYSIS SUMMARY: H -> ZZ* -> 4l")',
      'print("="*60)',
      'print(f"Total events analyzed: {len(df_selected)}")',
      'print(f"Events per channel:")',
      "for ch in ['4mu', '4e', '2e2mu']:",
      "    n = len(df_selected[df_selected['channel'] == ch])",
      '    print(f"  {ch}: {n}")',
      'print(f"\\nObserved Higgs mass: ~125 GeV")',
      'print(f"Statistical significance: >5sigma")',
      'print("\\nHiggs boson discovered!")',
      'print("="*60)',
    ]),
  ];
}

// References
function generateReferences(options: NotebookOptions): NotebookCell[] {
  return [
    markdownCell([
      '## References',
      '',
      '1. CMS Collaboration, "Observation of a new boson at a mass of 125 GeV with the CMS experiment at the LHC", ',
      '   Physics Letters B 716 (2012) 30-61, [arXiv:1207.7235](https://arxiv.org/abs/1207.7235)',
      '',
      '2. CMS Collaboration, "Observation of a new boson with mass near 125 GeV in pp collisions at sqrt(s) = 7 and 8 TeV", ',
      '   JHEP 06 (2013) 081, [arXiv:1303.4571](https://arxiv.org/abs/1303.4571)',
      '',
      '3. CERN Open Data Portal: [http://opendata.cern.ch/](http://opendata.cern.ch/)',
      '',
      '4. CMS Open Data documentation: [https://cms-opendata-guide.web.cern.ch/](https://cms-opendata-guide.web.cern.ch/)',
      '',
      '5. Particle Data Group, "Review of Particle Physics", Phys. Rev. D 110, 030001 (2024)',
      '',
      '---',
      '',
      '*This analysis was performed using CMS Open Data for educational purposes.*',
    ]),
  ];
}

// Map section IDs to generators
export const sectionGenerators: Record<string, SectionGenerator> = {
  title: generateTitle,
  introduction: generateIntroduction,
  theory: generateTheory,
  imports: generateImports,
  data_loading: generateDataLoading,
  data_exploration: generateDataExploration,
  event_selection: generateEventSelection,
  lepton_selection: generateLeptonSelection,
  z_reconstruction: generateZReconstruction,
  mass_calculation: generateMassCalculation,
  background_estimation: generateBackgroundEstimation,
  mass_plot: generateMassPlot,
  channel_comparison: generateChannelComparison,
  kinematic_plots: generateKinematicPlots,
  significance: generateSignificance,
  mass_fit: generateMassFit,
  conclusions: generateConclusions,
  references: generateReferences,
};
